/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Promotion;
import org.openapitools.model.PromotionUpdate;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-10-14T14:32:21.168513498+07:00[Asia/Bangkok]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "Promotions", description = "the Promotions API")
public interface PromotionsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PATCH /promotions/{promotionId} : Update promotion
     *
     * @param promotionId  (required)
     * @param promotionUpdate  (required)
     * @return Promotion updated (status code 200)
     */
    @Operation(
        operationId = "promotionsPromotionIdPatch",
        summary = "Update promotion",
        tags = { "Promotions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Promotion updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Promotion.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/promotions/{promotionId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Promotion> promotionsPromotionIdPatch(
        @Parameter(name = "promotionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("promotionId") Integer promotionId,
        @Parameter(name = "PromotionUpdate", description = "", required = true) @Valid @RequestBody PromotionUpdate promotionUpdate
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"end_date\" : \"2000-01-23T04:56:07.000+00:00\", \"promotion_name\" : \"promotion_name\", \"is_active\" : true, \"promotion_code\" : \"promotion_code\", \"club_id\" : 6, \"discount_value\" : 1.4658129805029452, \"promotion_id\" : 0, \"discount_type\" : \"discount_type\", \"start_date\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
