spring:
  application:
    name: billiard-api
  jpa:
    hibernate:
      ddl-auto: none       # dùng Flyway
    open-in-view: false
    properties:
      hibernate.format_sql: true
  jackson:
    time-zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

# profile docker sẽ override datasource
