spring:
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE:BillardManagement}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&connectionTimeZone=UTC
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:123123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
